version: "3"

services:

  fe:
    image: pmt_x_fe
    build: .

    command: python app.py

    environment:
      - FLASK_DEBUG=1

    ports:
      - 5000:5000

    volumes:
      - ./:/app:Z 


networks:
  default:
    name: pmt_x
    driver: bridge