version: "3"

services:

  fe:
    image: pmt_x_fe
    build: .

    command: flask run --host=0.0.0.0 --debug

    ports:
      - 5000:5000

    volumes:
      - ./:/app:Z 


networks:
  default:
    name: pmt_x
    driver: bridge