version: "3"

services:

  db:
    image: postgres:alpine

    restart: always

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example


  be:
    image: pmt_x_be
    build: ./backend/
    command: uvicorn main:app --reload --host 0.0.0.0

    ports:
      - 8000:8000

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pmtx
      DB_USER: postgres
      DB_PASS: example

    working_dir: /app/
    volumes:
      - ./backend/app:/app:Z


  fe:
    image: pmt_x_fe
    build: ./frontend/react/

    command: nodemon index.js -L #npm run dev

    ports:
      - 3000:3000

    working_dir: /app
    volumes:
      - ./frontend/react/app:/app:Z


networks:
  default:
    name: pmt_x
    driver: bridge
