version: "3"

services:

  db:
    image: postgres:alpine

    restart: always

    ports:
      - 11002:5432

    env_file: .env.local


  be:
    image: pmt_x_be
    build: ./backend/
    command: sh -c "service ssh start && uvicorn main:app --reload --host 0.0.0.0 --port 11001"
    # entrypoint: sh -c "service ssh start && sleep infinity"
    restart: always

    ports:
      - 11001:11001
      - 11011:22

    env_file: .env.local

    working_dir: /app/
    volumes:
      - ./backend/app:/app:Z
      - ./.env.local:/env/.env.local:ro


  # fe:
  #   image: pmt_x_fe
  #   build: ./frontend/react/

  #   command: nodemon index.js -L #npm run dev

  #   ports:
  #     - 3000:3000

  #   working_dir: /app
  #   volumes:
  #     - ./frontend/react/app:/app:Z


  fe:
    image: pmt_x_fe
    build: ./frontend/nextjs/

    entrypoint: sh -c "service ssh start && sleep infinity"
    restart: always

    ports: 
      - 11000:11000
      - 11010:22
    working_dir: /app
    volumes:
      - ./frontend/nextjs/app:/app:Z


networks:
  default:
    name: pmt_x
    driver: bridge
