version: "3"

services:

  fe:
    image: pmt_x_fe
    build: .

    working_dir: /app/project
    command: nodemon index.js -L #npm run dev

    ports:
      - 3000:3000

    volumes:
      - ./:/app:Z 

    stdin_open: true
    tty: true


networks:
  default:
    name: pmt_x
    driver: bridge